[package]
name = "binary_classification"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"

# Premature optimization is the root of all evil
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
